# Generated by Django 6.0 on 2026-01-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.PositiveIntegerField(choices=[(1, 'HEARTS'), (2, 'SPADES'), (3, 'DIAMONDS'), (4, 'CLUBS')])),
                ('rank', models.PositiveIntegerField(choices=[(1, 'ACE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE'), (6, 'SIX'), (7, 'SEVEN'), (8, 'EIGHT'), (9, 'NINE'), (10, 'TEN'), (11, 'JACK'), (12, 'QUEEN'), (13, 'KING')])),
                ('position', models.PositiveIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.deck')),
            ],
        ),
    ]
