# Generated by Django 6.0 on 2026-01-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blackjack', '0002_delete_card_delete_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=10)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackjack.round')),
            ],
        ),
    ]
